import { useFormik } from "formik";
import Head from "next/head";
import Image from "next/image";

const ProfilePassword = ({submitPassword, requestState, hideMessage}) => {
  const validate = values => {
    const errors = {};
    if (!values.oldPassword) {
      errors.oldPassword = 'Required';
    } else if (values.oldPassword.length < 6 || values.oldPassword.length > 25) {
      errors.oldPassword = 'Must be between 6 and 25 characters';
    }
    
    if (!values.newPassword) {
      errors.newPassword = 'Required';
    } else if (values.newPassword.length < 6 || values.newPassword.length > 25) {
      errors.newPassword = 'Must be between 6 and 25 characters';
    }

    if (!values.confirmPassword) {
      errors.confirmPassword = 'Required';
    } else if (values.confirmPassword !== values.newPassword) {
      errors.confirmPassword = 'Password do not match';
    }
    return errors;
  }

  const formik = useFormik({
    initialValues: {
      oldPassword: "",
      newPassword: "",
      confirmPassword: ""
    },
    validate,
    onSubmit: (values) => {
      submitPassword(values);
      hideMessage();
    },
  });

  return (
    <>
      <Head>
        <title>NutriLab - Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
        
      <>
        {/* Old Password */}
        <div className="relative my-2 w-full">
          <input
            type="password"
            id="oldPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.oldPassword && formik.touched.oldPassword && 'border-red-600 focus:border-red-600')
                      }
            placeholder=" "
            name="oldPassword"
            {...formik.getFieldProps('oldPassword')}
          />
          <label
            htmlFor="oldPassword"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-profile2
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.oldPassword && formik.touched.oldPassword && 'text-red-600 peer-focus:text-red-600')}
          >
            Current Password
          </label>
        </div>
        <div className="w-full mb-3 mt-1">
          <p className='text-xs text-red-600'>{formik.touched.oldPassword && formik.errors.oldPassword}</p>
        </div>

        {/* New Password */}
        <div className="relative my-2 w-full">
          <input
            type="password"
            id="newPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.newPassword && formik.touched.newPassword && 'border-red-600 focus:border-red-600')
                      }
            placeholder=" "
            name="newPassword"
            {...formik.getFieldProps('newPassword')}
          />
          <label
            htmlFor="newPassword"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-profile2
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.newPassword && formik.touched.newPassword && 'text-red-600 peer-focus:text-red-600')}
          >
            New Password
          </label>
        </div>
        <div className="w-full mb-3 mt-1">
          <p className='text-xs text-red-600'>{formik.touched.newPassword && formik.errors.newPassword}</p>
        </div>

        {/* Confirm Password */}
        <div className="relative my-2 w-full">
          <input
            type="password"
            id="confirmPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.confirmPassword && formik.touched.confirmPassword && 'border-red-600 focus:border-red-600')
                      }
            placeholder=" "
            name="confirmPassword"
            {...formik.getFieldProps('confirmPassword')}
          />
          <label
            htmlFor="confirmPassword"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-profile2
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.confirmPassword && formik.touched.confirmPassword && 'text-red-600 peer-focus:text-red-600')}
          >
            Confirm your Password
          </label>
        </div>
        <div className="w-full mb-3 mt-1">
          <p className='text-xs text-red-600'>{formik.touched.confirmPassword && formik.errors.confirmPassword}</p>
        </div>

        {requestState[0] === 0
        && <div className="w-full flex items-center p-4 text-gray-500 bg-red-500 rounded-lg shadow dark:text-gray-400 dark:bg-gray-800">
            <div className="ml-3 text-sm font-normal text-black">{requestState[1]}</div>
        </div>}
        {requestState[0] === 1
        && <div className="w-full flex items-center p-4 text-gray-500 bg-green-500 rounded-lg shadow dark:text-gray-400 dark:bg-gray-800">
            <div className="ml-3 text-sm font-normal text-black">{requestState[1]}</div>
        </div>}

        {/* Submit Button  */}
        <div className="my-4 w-full">
          <button
            onClick={formik.handleSubmit}
            type="button"
            className={`
                        mr-2 mb-2 rounded-lg border-2 border-[#4B4B4B] 
                        bg-custom-orange px-5 py-2.5 
                        text-sm font-medium text-[#4B4B4B] transition 
                        hover:border-gray-800 hover:text-gray-800 
                        focus:bg-gradient1 focus:border-black focus:text-black
                        dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 `+
                        ((formik.errors.email || formik.errors.username) && 'cursor-not-allowed')}
            disabled={formik.errors.email || formik.errors.username}
          >
            Edit
          </button>
        </div>
      </>
    </>
  );
};

export default ProfilePassword;
