import Head from "next/head";
import { BsGoogle, BsFacebook, BsTwitter } from "react-icons/bs";
import axios from "axios";
import { User_data } from "../context/context";
import { useContext } from "react";
import { useState } from "react";
import { useSession, signIn } from "next-auth/react";
import { useRouter } from "next/router";
import { useFormik } from "formik";

export default function Login({ setLogin, setAuth, setOpen }) {
  const router = useRouter();
  const { setUser } = useContext(User_data);
  const [error, setError] = useState({ email: "", password: "" });

  const validate = (values) => {
    const errors = {};

    if (!values.email) {
      errors.email = "Required";
    } else if (
      !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i.test(values.email)
    ) {
      errors.email = "Invalid email address";
    }

    if (!values.password) {
      errors.password = "Required";
    } else if (values.password.length < 6 || values.password.length > 25) {
      errors.password = "Must be between 6 and 25 characters";
    }

    return errors;
  };

  const formik = useFormik({
    initialValues: {
      email: "",
      password: "",
    },
    validate,
    onSubmit: (values) => {
      handleSubmit(values);
    },
  });

  const handleSubmit = async (values) => {
    const data = {
      email: values.email,
      password: values.password,
    };
    await axios
      .post("/api/login", data, {
        headers: {
          "Content-Type": "application/json",
        },
      })
      .then(async (response) => {
        setAuth(response.data);
        setOpen(false);
        if (router.query.path) {
          router.push(router.query.path);
        }

        setUser(response.data);
      })
      .catch((error) => {
        error.response.status === 401
          ? setError({ email: error.response.data.message })
          : setError({ password: error.response.data.message });
      });
  };
  return (
    <>
      <Head>
        <title>NutriLab - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      <div className="bg-white px-8 py-6 text-left shadow-lg ">
        <div className="flex justify-around">
          <button
            className="transition duration-300 ease-out hover:scale-125"
            onClick={() => signIn("google")}
          >
            <BsGoogle className="h-12 w-12 fill-orange-400 hover:fill-orange-600" />
          </button>
          <button
            className="transition duration-300 ease-out hover:scale-125"
            onClick={() => signIn("facebook")}
          >
            <BsFacebook className="h-12 w-12 fill-orange-400 hover:fill-orange-600" />
          </button>
          <button className="transition duration-300 ease-out hover:scale-125">
            <BsTwitter className="h-12 w-12 fill-orange-400 hover:fill-orange-600" />
          </button>
        </div>
        <div className="mt-7 mb-3 h-1 w-full bg-orange-400"></div>
        <h3 className="text-center text-2xl font-bold">Welcome back!</h3>
        <form action="">
          <div className="mt-4">
            <div className="relative flex flex-row">
              <div className=" flex basis-1/4 items-center">
                <label className="text-center" htmlFor="Email">
                  Email
                </label>
              </div>
              <input
                onFocus={() => setError({ ...error, email: "" })}
                type="text"
                placeholder="Email"
                name="email"
                {...formik.getFieldProps("email")}
                className={
                  "mt-2 w-max basis-3/4 rounded-md border px-4 py-2 focus:outline-none " +
                  (formik.errors.email &&
                    formik.touched.email &&
                    "border-red-600 focus:border-red-600")
                }
              />
              <p className="absolute left-20 -top-3 text-xs text-rose-500 sm:-top-4 sm:left-32 sm:text-sm">
                {formik.touched.email && formik.errors.email}
              </p>
              <p className="absolute left-20 -top-3 text-xs text-rose-500 sm:-top-4 sm:left-32 sm:text-sm">
                {error.email}
              </p>
            </div>
            <div className="relative mt-4 flex flex-row">
              <div className=" flex basis-1/4 items-center">
                <label className=" text-center">Password</label>
              </div>
              <input
                onFocus={() => setError({ ...error, password: "" })}
                type="password"
                placeholder="Password"
                name="password"
                {...formik.getFieldProps("password")}
                className={
                  "mt-2 w-full basis-3/4 rounded-md border px-4 py-2 focus:outline-none " +
                  (formik.errors.email &&
                    formik.touched.email &&
                    "border-red-600 focus:border-red-600")
                }
              />
              <p className="absolute left-20 -top-3 text-xs text-rose-500 sm:-top-4 sm:left-32 sm:text-sm">
                {formik.touched.password && formik.errors.password}
              </p>
              <p className="absolute left-20 -top-3 text-xs text-rose-500 sm:-top-4 sm:left-32 sm:text-sm">
                {error.password}
              </p>
            </div>

            <div className="flex">
              <button
                onClick={formik.handleSubmit}
                className="mt-4 w-full rounded-lg bg-orange-400 px-6 py-2 text-white hover:bg-orange-600"
              >
                Login to Account
              </button>
            </div>
            <div className="text-grey-dark mt-6">
              Don&apos;t have an account?
              <button
                className="text-orange-600 hover:underline"
                onClick={() => setLogin(false)}
              >
                Sign up
              </button>
            </div>
          </div>
        </form>
      </div>
    </>
  );
}
