import { useFormik } from "formik";
import Head from "next/head";
import Image from "next/image";

const ProfilePassword = () => {
  const validate = values => {
    const errors = {};
    return errors;
  }

  const formik = useFormik({
    initialValues: {
      oldPassword: "",
      newPassword: "",
      confirmPassword: "",
    },
    validate,
    onSubmit: (values) => {
      alert(JSON.stringify(values, null, 2));
    },
  });

  return (
    <>
      <Head>
        <title>NutriLab - Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      <div className="flex flex-col items-center justify-start md:w-1/2">
        <div className="my-16 flex items-center justify-center">
          <Image
            width={500}
            height={500}
            className="h-64 w-64 rounded-full object-cover object-center"
            src="/test.png"
            alt="Profile"
          />
        </div>

        {/* Old Password */}
        <div class="relative my-2 w-full">
          <input
            type="text"
            id="oldPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.oldPassword && 'border-red-500 focus:border-red-500')
                      }
            placeholder=" "
            name="oldPassword"
            onChange={formik.handleChange}
            value={formik.values.oldPassword}
          />
          <label
            htmlFor="username"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-[#4B4B4B]
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.oldPassword && 'text-red-500 peer-focus:text-red-500')}
          >
            Current Password
          </label>
        </div>

        {/* New Password */}
        <div class="relative my-2 w-full">
          <input
            type="text"
            id="newPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.newPassword && 'border-red-500 focus:border-red-500')
                      }
            placeholder=" "
            name="newPassword"
            onChange={formik.handleChange}
            value={formik.values.newPassword}
          />
          <label
            htmlFor="username"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-[#4B4B4B]
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.newPassword && 'text-red-500 peer-focus:text-red-500')}
          >
            New Password
          </label>
        </div>

        {/* Confirm Password */}
        <div class="relative my-2 w-full">
          <input
            type="text"
            id="confirmPassword"
            className={`
                        peer block w-full 
                        appearance-none rounded-lg border-2 border-gray-300 bg-transparent 
                        px-2.5 pb-2.5 pt-4 
                        text-sm text-white 
                        focus:border-custom-orange focus:outline-none focus:ring-0 
                        dark:border-gray-600 dark:text-white dark:focus:border-custom-orange `+
                        (formik.errors.confirmPassword && 'border-red-500 focus:border-red-500')
                      }
            placeholder=" "
            name="confirmPassword"
            onChange={formik.handleChange}
            value={formik.values.confirmPassword}
          />
          <label
            htmlFor="username"
            className={`
                        absolute top-2 left-1 z-10 
                        origin-[0] -translate-y-4 scale-75 transform bg-[#4B4B4B]
                        px-2 text-sm 
                        text-white duration-300 hover:cursor-text 
                        peer-placeholder-shown:top-1/2 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:scale-100 
                        peer-focus:top-2 peer-focus:-translate-y-4 peer-focus:scale-75 peer-focus:px-2 peer-focus:text-custom-orange 
                        dark:bg-gray-900 dark:text-gray-400 
                        peer-focus:dark:text-blue-500 `+ 
                      (formik.errors.confirmPassword && 'text-red-500 peer-focus:text-red-500')}
          >
            Confirm your Password
          </label>
        </div>
      </div>
    </>
  );
};

export default ProfilePassword;
