import Head from "next/head";
import Image from 'next/image';

const ProfilePage = () => {
  return (
    <>
      <Head>
          <title>NutriLab - Profile Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      <div className="md:w-1/2 flex flex-col justify-start items-center">
        <div className='flex justify-center items-center my-16'>
          <Image
              width={500}
              height={500}
              className="rounded-full w-64 h-64 object-center object-cover"
              src="/test.png"
          />
        </div>
        <div class="w-full md:w-2/3 my-2 relative">
            <input type="text" id="username" className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-white bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-custom-orange focus:outline-none focus:ring-0 focus:border-custom-orange peer" placeholder=" " />
            <label htmlFor="username" className="absolute hover:cursor-text text-sm text-white dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-[#4B4B4B] dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-custom-orange peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">Username</label>
        </div>
        <div class="w-full md:w-2/3 my-2 relative">
            <input type="email" id="email" className="block px-2.5 pb-2.5 pt-4 w-full text-sm text-white bg-transparent rounded-lg border-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-custom-orange focus:outline-none focus:ring-0 focus:border-custom-orange peer" placeholder=" " />
            <label htmlFor="email" className="absolute hover:cursor-text text-sm text-white dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-[#4B4B4B] dark:bg-gray-900 px-2 peer-focus:px-2 peer-focus:text-custom-orange peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 left-1">E-mail</label>
        </div>
        <div className="w-full md:w-2/3 my-4">
          <button type="button" className="text-gray-700 hover:text-black border-2 border-[#4B4B4B] bg-custom-orange transition hover:border-black focus:outline-none focus:ring-4 focus:ring-[#FFBB99] font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Edit</button>
        </div>
      </div>
    </>
  )
}

export default ProfilePage