import Head from "next/head";
import { useContext, useEffect, useState } from "react";

import { MdOutlineRemoveCircle } from "react-icons/md";

import { RiEditFill } from "react-icons/ri";
import { FaExternalLinkAlt } from "react-icons/fa";

import Navbar from "/components/Navbar";
import axios from "axios";
import { User_data } from "/context/context";
import Link from "next/link";
import AddDailyFood from "../components/addDailyFood";

// Irrelevent Fcts
function capitalizeFirstLetter(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}

function sliceUnderscore(string) {
  const splitted = string.split("_");
  const capitalized = splitted.map((string) => capitalizeFirstLetter(string));
  return capitalized.join(" ");
}

const Food = ({ food }) => {
  const [eatenFoodList, setEatenFoodList] = useState([]);
  const [isAlgorithmEnabled, setIsAlgorithmEnabled] = useState(false);

  const { user, setUser } = useContext(User_data);

  // Next is SSR, so we should ... , Force a render with useEffect
  const [localNutris, setLocalNutris] = useState(false);
  const [localInfos, setLocalInfos] = useState(false);
  useEffect(() => {
    setLocalNutris(JSON.parse(window.localStorage.getItem("nutris")));
    setLocalInfos(JSON.parse(window.localStorage.getItem("dietInfos")));
  }, []);

  //Handle API changes
  const [algoData, setAlgoData] = useState({});

  const laboTable1 = eatenFoodList.map((food) => {
    return (
      <tr
        key={food.name}
        class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
      >
        <th
          scope="row"
          class="px-6 py-4 font-bold text-gray-900 whitespace-nowrap dark:text-white truncate hover:whitespace-normal sm:whitespace-normal"
        >
          {food.name}
        </th>
        <td class="px-3 py-4 underline font-black text-lg truncate whitespace-normal">
          {food.size}g
        </td>
      </tr>
    );
  });

  const laboTable2 =
    Object.keys(algoData).length !== 0 &&
    Object.keys(algoData).map((food) => {
      console.log(food);
      return (
        <tr
          key={food.name}
          class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
        >
          <th
            scope="row"
            class="px-6 py-4 font-bold text-gray-900 dark:text-white truncate whitespace-normal sm:whitespace-normal"
          >
            {food.slice(1).split("_").join(" ")}
          </th>
          <td class="px-3 py-4 underline font-black text-lg truncate whitespace-nowrap">
            {/* {100 * algoData[food]} g */}
            {(Math.round(100 * algoData[food] * 100) / 100).toFixed(2)}g
          </td>
        </tr>
      );
    });
  // const laboTable3 = treatedFoodList.map((food) => {
  const laboTable3 =
    Object.keys(algoData).length !== 0 &&
    Object.keys(algoData).map((food) => {
      console.log(food);
      return (
        <tr
          key={food.name}
          class="bg-white border-b dark:bg-gray-800 dark:border-gray-700"
        >
          <th
            scope="row"
            class="text-green-500 px-6 py-4 font-bold  whitespace-nowrap dark:text-white truncate hover:whitespace-normal sm:whitespace-normal"
          >
            {food.slice(1).split("_").join(" ")}
          </th>
          <td class="px-3 py-4 underline font-black text-lg truncate whitespace-normal text-green-500">
            +{(Math.round(100 * algoData[food] * 100) / 100).toFixed(2)}g
          </td>
        </tr>
      );
    });

  // ---------------------------------------------------------------------------------------------------------------

  return (
    <div>
      <Head>
        <title>NutriLab - Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>

      <Navbar User={user} />
      <AddDailyFood
        food={food}
        eatenFoodList={eatenFoodList}
        setEatenFoodList={setEatenFoodList}
        setAlgoData={setAlgoData}
        setIsAlgorithmEnabled={setIsAlgorithmEnabled}
      />
      {/* Check Your Informations  */}
      <div
        className="
                        flex flex-col justify-center items-center
                        sm:col-start-2 col-span-8 sm:col-span-6
                        border-2 border-custom-orange rounded
                        w-full my-16"
      >
        <h3 className="font-title text-3xl xs:text-4xl sm:text-5xl text-center | w-full my-16">
          Check Your Informations
        </h3>
        <div className="flex justify-between items-center">
          <h4 className="font-title text-2xl xs:text-3xl sm:text-4xl text-center | w-full">
            Your Input Infos
          </h4>
          <Link href="/nutrients">
            <RiEditFill
              size={25}
              className="hover:fill-custom-orange transition duration-300 ml-2"
            />
          </Link>
        </div>
        {localInfos ? (
          <div className="flex-2 flex justify-center items-center border rounded my-4">
            <table className="w-full text-sm text-left text-gray-500">
              <tbody>
                <tr className="bg-white border-b">
                  <th
                    scope="row"
                    className="px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Age
                  </th>
                  <td className="px-6 py-4 truncate">
                    {localInfos.age || "No Entry"}
                  </td>
                </tr>

                <tr className="border-b bg-gray-50">
                  <th
                    scope="row"
                    className="px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Sex
                  </th>
                  <td className="px-6 py-4 truncate">
                    {capitalizeFirstLetter(localInfos.sex) || "No Entry"}
                  </td>
                </tr>

                <tr className="bg-white border-b">
                  <th
                    scope="row"
                    className="px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Height
                  </th>
                  <td className="px-6 py-4 truncate">
                    {localInfos.height || "No Entry"}
                  </td>
                </tr>

                <tr className="border-b bg-gray-50">
                  <th
                    scope="row"
                    className="px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Weight
                  </th>
                  <td className="px-6 py-4 truncate">
                    {localInfos.weight || "No Entry"}
                  </td>
                </tr>

                <tr className="border-b bg-white">
                  <th
                    scope="row"
                    className="text-center px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Activity
                  </th>
                  <td className="px-6 py-4 truncate">
                    {sliceUnderscore(localInfos.activity) || "No Entry"}
                  </td>
                </tr>

                <tr className="bg-gray-50">
                  <th
                    scope="row"
                    className="text-center px-6 py-4 text-gray-900 whitespace-nowrap"
                  >
                    Plan
                  </th>
                  <td className="px-6 py-4 truncate">
                    {sliceUnderscore(localInfos.plan) || "No Entry"}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        ) : (
          <div className="flex justify-center items-center border rounded my-8">
            <span>
              <b className="font-paragraph font-medium text-sm">
                It seems you have yet to tell us about you,{" "}
              </b>
              <Link href="/nutrients">
                <b className="font-paragraph font-black text-sm hover:underline hover:text-custom-orange transition duration-300">
                  click here
                </b>
              </Link>
            </span>
          </div>
        )}

        <div className="flex justify-between items-center">
          <h4 className="font-title text-2xl xs:text-3xl sm:text-4xl text-center | w-full">
            Your generated Infos
          </h4>
          <Link href="/nutrients">
            <RiEditFill
              size={25}
              className="hover:fill-custom-orange transition duration-300 ml-2"
            />
          </Link>
        </div>

        {localNutris ? (
          <div className="flex my-8 overflow-x-auto no-scrollwbar w-11/12">
            <table class="w-full text-sm text-left text-gray-500">
              <thead class="text-xs text-gray-700 uppercase">
                <tr>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-700">
                    Calories
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-800">
                    Proteins
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-700">
                    Carbs
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-800">
                    Fats
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-700">
                    Fiber
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-800">
                    Salt
                  </th>
                  <th scope="col" class="px-6 py-3 text-white bg-gray-700">
                    Sugar
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr class="border-b border-gray-200 dark:border-gray-700">
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-100">
                    {localNutris.kCalories} kCal
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {localNutris.proteins} g
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-100">
                    {localNutris.carbs} g
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {localNutris.fats} g
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-100">
                    {localNutris.fiber} g
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {localNutris.salt} g
                  </td>
                  <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap bg-gray-100">
                    {localNutris.sugar} g
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        ) : (
          <div className="flex justify-center items-center border rounded my-8">
            <span>
              <b className="font-paragraph font-medium text-sm">
                You haven't yet generated your daily nutrients ,{" "}
              </b>
              <Link href="/nutrients">
                <b className="font-paragraph font-black text-sm hover:underline hover:text-custom-orange transition duration-300">
                  click to apply your infos
                </b>
              </Link>
            </span>
          </div>
        )}
      </div>

      {/* Food Algorithm  */}
      {isAlgorithmEnabled && (
        <div
          id="algorithm"
          className="
                        flex flex-col justify-center items-center
                        sm:col-start-2 col-span-8 sm:col-span-6
                        border-2 border-custom-orange rounded
                        w-full mb-16"
        >
          <h3 className="font-title text-3xl xs:text-4xl sm:text-5xl text-center | w-full my-16">
            Your Labo
          </h3>
          <div className="flex items-stretch justify-between w-full mb-4">
            <div className="flex-1 border-2 border-custom-orange flex flex-col justify-start items-center w-full mx-2">
              <p className="font-paragraph font-bold text-xl text-black my-4">
                Previous Diet
              </p>

              <div className="border-b-2 border-custom-orange w-full"></div>

              <table class="w-full text-sm text-left text-black dark:text-white font-logo">
                <tbody>{laboTable1}</tbody>
              </table>
            </div>

            <div
              className="
                          border-2 border-custom-orange 
                          flex-1 flex flex-col justify-start items-center 
                          w-full mx-2
                          
            "
            >
              <div className="bg-gradient-to-r from-gradient1 to-gradient2 w-full text-center">
                <p className="font-paragraph font-bold text-xl text-white my-4">
                  Changes Made
                </p>
              </div>

              <div className="border-b-2 border-custom-orange w-full"></div>

              <table class="w-full text-sm text-left text-black dark:text-white font-logo">
                <tbody>{laboTable2}</tbody>
              </table>
            </div>

            <div
              className="
                          border-2 border-custom-orange 
                          flex-1 flex flex-col justify-start items-center 
                          w-full mx-2
                          
            "
            >
              <div className="bg-gradient-to-r from-gradient1 to-gradient2 w-full text-center">
                <p className="font-paragraph font-bold text-xl text-white my-4">
                  New Diet
                </p>
              </div>

              <div className="border-b-2 border-custom-orange w-full"></div>

              <table class="w-full text-sm text-left text-black dark:text-white font-logo">
                <tbody>{laboTable1}</tbody>
                <tbody>{laboTable3}</tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Food;

export const getStaticProps = async () => {
  const url =
    process.env.VERCEL_ENV === "production"
      ? "https://nutrilab.vercel.app/api/food"
      : "http://localhost:3000/api/food";
  const res = await axios.get(url);
  const food = await res.data;

  return {
    props: {
      food,
    },
  };
};
