import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import getCookie from "next-cookies";

import { useContext, useEffect } from "react";
import { MdDoubleArrow } from "react-icons/md";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

import { User_data } from "../context/context";

import styles from "../styles/Home.module.css";

export default function Home() {
  const { user, setUser } = useContext(User_data);
  return (
    <div>
      <Head>
        <title>NutriLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      {/* <Navbar /> */}
      <Navbar User={user} />
      <div className="mx-auto w-full">
        <div className="flex items-center justify-center bg-gradient-to-b from-gradient1 via-gradient2 to-transparent">
          <div className="m-4 flex flex-1 flex-col items-center justify-center space-y-8 sm:m-12 lg:m-28">
            <h1 className="mt-4 w-full font-title text-5xl sm:text-8xl">
              What do we do
            </h1>
            <div className="flex flex-1 items-center justify-center sm:hidden">
                <Image
                  width={1000}
                  height={1000}
                  priority
                  // as="image"
                  // rel="preload"
                  className="h-80 w-96 rounded-lg object-cover"
                  src="https://i.ibb.co/QbZ0WC9/science1.jpg"
                  alt="science1"
                />
            </div>
            <p className="text-md text-left indent-2 font-paragraph">
              NutriLab uses science to help you find your optimized combination
              of food that will make you meet your daily needs of nutrients
              based on your body, activity, plan and food preferences.
            </p>
            <p className="text-md text-left indent-2 font-paragraph">
              <b>Measure your daily need of nutrients</b>,{" "}
              <b>Balance your food</b> and{" "}
              <b>let us help you find today&apos;s meal</b>.
            </p>
            <div className="flex w-full items-center justify-center sm:justify-end">
              <Link href="/nutrients">
                <div
                  className="relative max-w-xs overflow-hidden rounded-2xl bg-cover  bg-no-repeat "
                  // style={{ backgroundColor: "#DCF8FF" }}
                >
                  <button className=" rounded-2xl border-4 border-custom-orange bg-white py-2 px-5 text-4xl font-bold text-custom-orange sm:py-4 sm:px-9 sm:text-lg sm:font-extrabold">
                    Start
                  </button>
                  {/* <div className="absolute top-0 right-0 bottom-0 left-0 h-full w-full overflow-hidden bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 opacity-0 transition duration-300 ease-in-out hover:opacity-70"></div> */}
                </div>
              </Link>
            </div>
          </div>
          <div className="my-28 mx-12 hidden flex-1 items-center justify-center sm:flex">
            <a href="https://ibb.co/xCyZnfh">
              <Image
                width={1000}
                height={1000}
                priority
                // as="image"
                // rel="preload"
                className="h-64 w-72 rounded-lg object-cover md:h-80 md:w-96"
                src="https://i.ibb.co/QbZ0WC9/science1.jpg"
                alt="science1"
              />
            </a>
          </div>
        </div>

        <div className="relative my-40 mx-3 grid grid-cols-8">
          <Image
            width={125}
            height={125}
            src="/icons/diet.png"
            alt="decor"
            className="
                          absolute 
                          -top-20 left-20 rotate-[28deg] animate-rotate_normal opacity-[0.44] md:top-0"
          />
          <div
            className="
                          absolute top-80 -left-10
                          hidden h-32 w-32 md:block md:animate-rotate_normal"
          >
            <Image
              width={125}
              height={125}
              src="/icons/plan.png"
              alt="decor"
              className="
                          absolute top-10 hidden
                          rotate-0 opacity-[0.44] md:block md:animate-rotate_reverse"
            />
          </div>
          <Image
            width={125}
            height={125}
            src="/icons/order-food.png"
            alt="decor"
            className="
                        absolute
                        top-72 right-28 rotate-[33deg] animate-translate_right opacity-[0.44]"
          />
          <Image
            width={125}
            height={125}
            src="/icons/meal.png"
            alt="decor"
            className="
                        absolute 
                        bottom-64 left-10 rotate-0 animate-rotate2_reverse opacity-[0.44] md:bottom-44"
          />
          <Image
            width={125}
            height={125}
            src="/icons/balanced-diet.png"
            alt="decor"
            className="
                        absolute
                        -bottom-8 right-1/3 rotate-0 animate-translate_bottom opacity-[0.44]"
          />
          <Image
            width={125}
            height={125}
            src="/icons/healthy-food.png"
            alt="decor"
            className="
                        absolute bottom-44 right-12 
                        hidden rotate-[14deg] opacity-[0.44] md:block md:animate-rotate3"
          />
          <div className="| | z-10 col-span-8 flex flex-col items-center justify-center space-y-8 xm:col-span-6 xm:col-start-2">
            <div
              className={
                "flex h-80 w-full max-w-6xl items-center justify-center rounded-2xl " +
                styles.dropshadow
              }
            >
              <div className="item-start mt-8 flex h-full flex-1 flex-col justify-start">
                <b className="m-4 text-4xl font-black xs:text-5xl">
                  Customized Nutrients
                </b>
                <p className="m-4 font-paragraph">
                  Measure your daily needed nutrients based on your age, sex,
                  height, weight, activity level and your personal plan.
                </p>
                <Link href="/nutrients">
                  <MdDoubleArrow
                    className="mx-4 cursor-pointer transition duration-300 hover:fill-custom-orange lg:m-4"
                    size={50}
                  />
                </Link>
              </div>
              <div
                className={
                  "hidden rounded-tr-2xl rounded-br-2xl xs:block " +
                  styles.polygon1
                }
              ></div>
            </div>

            <div
              className={
                "flex h-80 w-full max-w-6xl items-center justify-center rounded-2xl " +
                styles.dropshadow
              }
            >
              <div
                className={
                  "hidden rounded-tl-2xl rounded-bl-2xl xs:block " +
                  styles.polygon2
                }
              ></div>
              <div className="item-start mt-8 flex h-full flex-1 flex-col justify-start">
                <b className="m-4 text-4xl font-black xs:text-5xl">
                  Food Generated
                </b>
                <p className="m-4 font-paragraph">
                  Based on your daily intake of food, we will provide you the
                  best combination of food to meet your daily needs of
                  nutrients.
                </p>
                <Link href="/foodProcess">
                  <MdDoubleArrow
                    className="mx-4 cursor-pointer transition duration-300 hover:fill-custom-orange lg:m-4"
                    size={50}
                  />
                </Link>
              </div>
            </div>

            <div
              className={
                "flex h-80 w-full max-w-6xl items-center justify-center rounded-2xl " +
                styles.dropshadow
              }
            >
              <div className="item-start mt-8 flex h-full flex-1 flex-col justify-start">
                <b className="m-4 text-4xl font-black xs:text-5xl">
                  Suggested Meals
                </b>
                <p className="m-4 font-paragraph">
                  Using the balanced combination of food generated, we can help
                  you find today&apos;s meal.
                </p>
              </div>
              <div
                className={
                  "hidden rounded-tr-2xl rounded-br-2xl xs:block " +
                  styles.polygon3
                }
              ></div>
            </div>
          </div>
        </div>

        <div className="mx-3 grid grid-cols-8">
          <div
            className={
              "| | | col-span-8 flex flex-col items-center justify-center rounded-xl md:col-span-6 md:col-start-2 " +
              styles.dropshadow
            }
          >
            <b className="my-16 text-center font-title text-4xl">
              The Tools for Your Goals
            </b>
            <div className="flex flex-col items-center justify-center sm:flex-row">
              <div className="m-4 flex h-full flex-1 flex-col items-center justify-start xm:m-8 xl:m-16">
                <a href="https://imgbb.com/">
                  <Image
                    width={1000}
                    height={1000}
                    className="my-8 h-32 w-32 rounded-xl drop-shadow-md"
                    src="https://i.ibb.co/0c2vhFr/nutrients.png"
                    alt="nutrients"
                  />
                </a>
                <p className="max-w-xs text-center font-paragraph">
                  Helps you measure your calories and nutrients needed.
                </p>
              </div>
              <div className="m-4 flex h-full flex-1 flex-col items-center justify-start xm:m-8 xl:m-16">
                <a href="https://imgbb.com/">
                  <Image
                    width={1000}
                    height={1000}
                    className="my-8 h-32 w-32 rounded-xl drop-shadow-md"
                    src="https://i.ibb.co/pJKG4T7/balanced-diet.png"
                    alt="balanced-diet"
                  />
                </a>
                <p className="max-w-xs text-center font-paragraph">
                  Helps you find the most balanced combination of food based on
                  your preferences.
                </p>
              </div>
              <div className="m-4 flex h-full flex-1 flex-col items-center justify-start xm:m-8 xl:m-16">
                <a href="https://imgbb.com/">
                  <Image
                    width={1000}
                    height={1000}
                    className="my-8 h-32 w-32 rounded-xl drop-shadow-md"
                    src="https://i.ibb.co/s5dkt00/recommended-food.png"
                    alt="recommended-food"
                  />
                </a>
                <p className="max-w-xs text-center font-paragraph">
                  Suggests for you the possible meals based on the generated
                  combination of balanced food.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* <HowItsBuilt /> */}

        <Footer />
      </div>
    </div>
  );
}
