import Navbar from "../components/Navbar";
import { useRouter } from "next/router";
import Head from "next/head";
export default function Home() {
  return (
    <div>
      <Head>
        <title>NutriLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      {/* <Register /> */}
      <Navbar />
      {/* <Login /> */}
      {/* <Navbar />

      <Hero />
      <PickOne reload={() => router.push("/Loading")} ayoub="ayoub" />
      <Footer /> */}
    </div>
  );
}
