import Navbar from "../components/Navbar";
import isAuthenticated from "./api/Auth";
import getCookie from "next-cookies";
import Head from "next/head";
export default function Home({ user }) {
  return (
    <div>
      <Head>
        <title>NutriLab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      {/* <Register /> */}
      <Navbar User={user} />
      {/* <Login /> */}
      {/* <Navbar />

      <Hero />
      <PickOne reload={() => router.push("/Loading")} ayoub="ayoub" />
      <Footer /> */}
    </div>
  );
}
Home.getInitialProps = async (context) => {
  const { NutriLab } = getCookie(context);
  const user = isAuthenticated(NutriLab);
  if (!user) {
    return { user: false };
  }
  return { user: user };
};
