import Head from "next/head";

import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HowItsBuilt from "../components/HowItsBuilt";
import DietInfo from "../components/DietInfo";
import DailyNutrients from "../components/DailyNutrients";
import { useState } from "react";

const Nutrients = ({ user }) => {
  const [isInfosApplied, setIsInfosApplied] = useState(false);

  const applyInfos = (dietInfos) => {
    const { age, sex, height, weight, activity } = dietInfos;

    setIsInfosApplied(true);
  };

  return (
    <div>
      <Head>
        <title>NutriLab - Nutrients</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>

      {/* Nutrients Page  */}
      <Navbar User={user} />

      <div className="grid grid-cols-6 justify-items-center">
        <div className="flex flex-col justify-center items-center | sm:col-start-2 xl:col-start-3 col-span-6 sm:col-span-4 xl:col-span-2 | max-w-xl mx-4">
          <h1 className="font-title text-6xl text-center | w-full my-16">
            Let us know You
          </h1>
          <DietInfo
            handleApply={applyInfos}
            flushInfos={() => setIsInfosApplied(false)}
            isInfosApplied={isInfosApplied}
          />
        </div>
      </div>

      <div className="grid grid-cols-8">
        {isInfosApplied && <DailyNutrients />}
      </div>

      <HowItsBuilt />

      <Footer />
    </div>
  );
};

export default Nutrients;
