import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react'

const foodInfos = ({foodData}) => {
    const router = useRouter();
    const url = router.asPath;
    const id = url.split('/food/')[1];
  return (
    <div>
      <Head>
        <title>NutriLab - Food</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.ibb.co/yhHmPr0/orange-slice.png" />
      </Head>
      <div className="">{foodData.name}</div>
    </div>
  )
}

export default foodInfos

export const getServerSideProps = async (context) => {
    const res = await fetch(
        `${process.env.SERVER}/api/food/${context.params.id}`
    )
    const foodData = await res.json();

    return {
        props: {
          foodData,
        },
      };
}